In [1]:
import torch
import numpy as np

### 数据基本操作，元素类型，tensor形状等

In [4]:
a=torch.tensor([1,2,3],dtype=int)
print(a,a.dtype)
tensor=torch.tensor([[1,2,3],
                     [4,5,6]])
print(tensor.ndim)
print(tensor.shape,tensor.size())

tensor([1, 2, 3]) torch.int64
2
torch.Size([2, 3]) torch.Size([2, 3])


### 数据生成

In [7]:
print(torch.ones(3,4))#生成全一tensor
print(torch.zeros(3,4))#生成全零tensor
print(torch.rand(3,4))#生成0-1之间的随机tensor
print(torch.randint(0,10,(2,3)))#生成随机整数tensor
print(torch.randn(3,4))#符合正态分布的随机数
a=torch.randint(0,10,(4,3))
print(a)
print(torch.rand_like(a,dtype=float))#生成和a形状一样的tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.3504, 0.1234, 0.1594, 0.4151],
        [0.5036, 0.7950, 0.2883, 0.4391],
        [0.6728, 0.8382, 0.2310, 0.6426]])
tensor([[2, 3, 9],
        [8, 9, 8]])
tensor([[-0.3247, -0.4076, -1.4892, -0.1831],
        [-0.6597, -0.7731,  0.8686, -0.3223],
        [ 0.6097,  1.4915,  1.0128, -2.0191]])
tensor([[4, 9, 1],
        [8, 5, 4],
        [2, 5, 8],
        [2, 4, 2]])
tensor([[0.1545, 0.6235, 0.1608],
        [0.2350, 0.1919, 0.2413],
        [0.3824, 0.1350, 0.0042],
        [0.8935, 0.1213, 0.4845]], dtype=torch.float64)


In [10]:
a=torch.randint(0,10,(2,3))
b=a.view(6)
c=a.view(3,2)
print("a={}\nb={}\nc={}\n".format(a,b,c))

a=tensor([[1, 0, 3],
        [8, 5, 4]])
b=tensor([1, 0, 3, 8, 5, 4])
c=tensor([[1, 0],
        [3, 8],
        [5, 4]])



### 数据类型转换

In [13]:
d=np.array(a)
e=torch.tensor(d)
print("d={}\ne={}\n".format(d,e))

d=[[1 0 3]
 [8 5 4]]
e=tensor([[1, 0, 3],
        [8, 5, 4]])



### 基本运算操作

In [21]:
#任何使tensor发生变化的操作都会有前缀 “_”
a=torch.randint(0,10,(2,3),dtype=float)
b=torch.ones(2,3)
print("a={}\nb={}".format(a,b))
#a=a+b
a.add_(b)
print("a={}\nb={}".format(a,b))
print(a*b)#对应位置相乘
print(a%b)#对应位置取余
print(a//b)#对应位置整除
print(b.T)#转置
print(a)
a=a.float()
b=b.float()

a=tensor([[6., 9., 4.],
        [2., 9., 8.]], dtype=torch.float64)
b=tensor([[1., 1., 1.],
        [1., 1., 1.]])
a=tensor([[ 7., 10.,  5.],
        [ 3., 10.,  9.]], dtype=torch.float64)
b=tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[ 7., 10.,  5.],
        [ 3., 10.,  9.]], dtype=torch.float64)
tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[ 7., 10.,  5.],
        [ 3., 10.,  9.]], dtype=torch.float64)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[ 7., 10.,  5.],
        [ 3., 10.,  9.]], dtype=torch.float64)
a=tensor([[ 7., 10.,  5.],
        [ 3., 10.,  9.]])
b=tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[22., 22.],
        [22., 22.]])
tensor(44.)
tensor(3.) tensor(10.)
tensor(3) tensor(1)


In [26]:
a=torch.randint(0,10,(2,3),dtype=float)
b=torch.ones(2,3)
a=a.float()
print("a={}\nb={}".format(a,b))
print(torch.matmul(a,b.T))#矩阵相乘，注意两个矩阵元素dtype相同
print(torch.sum(a))#矩阵所有元素求和，返回一个tensor
print(torch.min(a),torch.max(a))#返回最大值和最小值，返回tensor
print(torch.argmin(a),torch.argmax(a))#返回最小值的索引
print(torch.mean(a))#返回a矩阵所有元素的均值，返回tensor
print(torch.median(a))#中位数，返回tensor

a=tensor([[2., 6., 2.],
        [3., 1., 2.]])
b=tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[10., 10.],
        [ 6.,  6.]])
tensor(16.)
tensor(1.) tensor(6.)
tensor(4) tensor(1)
tensor(2.6667)
tensor(2.)


### 数据的索引

In [32]:
te=torch.arange(2,14)#左闭右开
print(te)
print(te[2])
print(te[1:4])
print(te[:5])#不做特殊说明，冒号左边没有数据就是从开头取，冒号右边没有就是取到最后

tensor([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])
tensor(4)
tensor([3, 4, 5])
tensor([2, 3, 4, 5, 6])


### 自动求导

定义一个Output=$\frac{1}{4}\sum_{i}z_{i}$,其中$z=3(x_i +2)^2$且有$z_i |_{x_i =1}=27$,因此$\frac{\partial output}{\partial x_i}=\frac{3}{2}(x+2)$,所以$\frac{\partial output}{\partial x_i}|_{x_i =1}=\frac{9}{2}=4.5$

In [37]:
x=torch.ones((2,2),requires_grad=True)#定义一个tensor，设置可计算梯度
y=x+2
z=y*y*3
out=z.mean()
print(out)

tensor(27., grad_fn=<MeanBackward0>)


In [38]:
out.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])
